### PR TITLE
added copy linear-gradient code functionality

### PR DESCRIPTION
**Pull request by Keith-Web3**
## Issue it solved
#30 Added copy button to improve the user experience when copying the generated linear gradient

## Which files you changed?

backgroundgen.js, backgroundgen.css, index.html, added copy-icon.svg

I added a copy button which when clicked, copies the textcontent of the h3 element which is the linear-gradient code container

### CODE REVIEW

**Comment by Keith-Web3** [comment]
[Nirbhayparmar](https://github.com/Nirbhayparmar) kindly look into this

**Comment by Nirbhayparmar** [comment]
Can you attach the screenshot that how it is looking on small screens and large screens?

**Comment by Keith-Web3** [comment]
> Can you attach the screenshot that how it is looking on small screens and large screens?
> Small screens
Screenshot (5)

>Medium screens 
Screenshot (6)

>Large screens
Screenshot (7)

As regards the large screen, there's an issue with the github link overlapping with the rgb color making it impossible to use the copy button or to select and copy manually.

**Comment by Keith-Web3** [comment]
@Nirbhayparmar kindly review this and the issue of the github link overlapping with linear-gradient code.

**Comment by Nirbhayparmar** [comment]
Can you first solve that overlapping problem because it is not looking good.

**Comment by Keith-Web3** [comment]
Ok. Will do so now

**Comment by Keith-Web3** [comment]
@Nirbhayparmar I've fixed the overlapping issue. Kindly review it.
Here's a screenshot below
Screenshot (14)

**Comment by Nirbhayparmar** [comment]
ok will check this asap.

**Comment by Keith-Web3** [comment]
Okay

**Comment by Keith-Web3** [comment]
@Nirbhayparmar If you find the code good enough, you could close issue #30  and #32 as the two issues have been fixed in the code.

**Review by Nirbhayparmar — APPROVED** [review]
Your changes are good. Approving it.

**Comment by Nirbhayparmar** [comment]
Sorry for making you wait but I needed to be sure about what am I merging, by the way thank you for contributing to my project.

merging your PR.

**Comment by Keith-Web3** [comment]
No problem. It's all for the good of the project 👍

**Pull request merged**
