### PR TITLE
I have Changed the CSS

### PR DESCRIPTION
**Pull request by NayakPenguin**
## Issue it solved
I was not working on any issue as such but I have changed the website UI. I mainly changed the CSS portion, now the website looks way more professional. 

## Which files you changed?
backgroundgen.css

I have edited the CSS code which was earlier available. Few of the main things which I have worked on are the :
1. Font style and text widths
2. Component backgrounds 
3. Hover effects like on button
4. Shadow on button 
5. Bottom Github Image

### CODE REVIEW

**Comment by NayakPenguin** [comment]
I think the Image has not been uploaded, this https://ibb.co/BcRFG7Q is the final UI I have created.

**Comment by NayakPenguin** [comment]
@Nirbhayparmar @Jimmy-Taravia2001 @MahmmadhusenDodiya @lovelacecoding please review this

**Comment by Nirbhayparmar** [comment]
I like the changes you have done as seen from the given image, can you also send screenshot of this site on smaller screen layout to check how it is looking in smaller screens?

**Comment by NayakPenguin** [comment]
I have actually not made the changes responsive till now, but since you asked - I will start working on that now.

**Comment by NayakPenguin** [comment]
Screenshot 2022-10-01 at 11 27 12 PM

This is the current responsive design for small mobile devices. There are a few more changes that can be made like replacing the radio buttons with manual CSS buttons for the UI to look even better.

**Comment by Nirbhayparmar** [comment]
Can you make radio buttons in one column(in same verticle line) to make it more readable?

**Comment by NayakPenguin** [comment]
@Nirbhayparmar I have now made the radio buttons in one column, please merge this code. 
Screenshot 2022-10-02 at 4 46 56 PM

**Comment by Nirbhayparmar** [comment]
Thank you for this css changes.

**Pull request merged**
